# sonar-project.properties
# SonarQube scanner config.
# This file tells the sonar-scanner CLI where your code is
# and what project to report under.
# Place this in the ROOT of your project (same level as Jenkinsfile).

sonar.projectKey=devgordon
sonar.projectName=DevGordon
sonar.projectVersion=1.0

# Where the source code is
sonar.sources=app

# Tell SonarQube this is Python
sonar.language=py
sonar.python.version=3.11

# Exclude things that shouldn't be scanned
sonar.exclusions=app/static/**,**/__pycache__/**,**/*.pyc

# Encoding
sonar.sourceEncoding=UTF-8
